Implement custom error message in CI workflow
Add a custom error check in the CI workflow.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,6 +36,13 @@ jobs:
           cd sim
           chmod +x run.sh
           ./run.sh 
+      - name: Check for errors
+        run: |
+          if [ error ]; then
+          echo "::error::This is my custom error message!"
+          exit 1
+          fi
+
       - name: save logs
         if: always()
         uses: actions/upload-artifact@v4
